# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BidmadSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidmadSwiftUI
  pod 'BidmadAdFitAdapter', '3.12.7.5'
  pod 'BidmadADOPCoupangAdapter', '1.0.0.5'
  pod 'BidmadAdPopcornAdapter', '2.6.5.5'
  pod 'BidmadAllianceInternetAdapter', '1.0.0.5'
  pod 'BidmadAppLovinAdapter', '12.2.1.5'
  pod 'BidmadAtomAdapter', '1.0.0.5'
  pod 'BidmadFyberAdapter', '8.2.6.5'
  pod 'BidmadGoogleAdManagerAdapter', '11.2.0.5'
  pod 'BidmadGoogleAdMobAdapter', '11.2.0.5'
  pod 'BidmadIronSourceAdapter', '7.8.0.0.5'
  pod 'BidmadMobonAdapter', '0.6.17.5'
  pod 'BidmadPangleAdapter', '5.8.0.7.5'
  pod 'BidmadPartners/AdMobBidding', '1.0.4'
  pod 'BidmadPubmaticAdapter', '3.2.0.5'
  pod 'BidmadSDK', '6.7.0'
  pod 'BidmadTeadsAdapter', '5.0.27.5'
  pod 'BidmadUnityAdsAdapter', '4.9.3.5'
  pod 'BidmadVungleAdapter', '7.2.2.5'
  pod 'OpenBiddingHelper', '6.7.0'

end
