# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BidmadSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidmadSwiftUI
  pod 'BidmadSDK', '6.1.0'
  pod 'OpenBiddingHelper', '6.1.0'
  pod 'BidmadAdapterDynamic', '6.1.0'

end
